export const SCHEDULES_LOADING = "SCHEDULES_LOADING";
export const SCHEDULES_LOADING_FAILED = "SCHEDULES_LOADING_FAILED";
export const SHOW_ALL_SCHEDULES = "SHOW_ALL_SCHEDULES";
export const ADD_NEW_SCHEDULE_FAILED = "ADD_NEW_SCHEDULE_FAILED";
export const EDIT_SCHEDULE_FAILED = "EDIT_SCHEDULE_FAILED";
export const DELETE_SCHEDULE_FAILED = "DELETE_SCHEDULE_FAILED";
