export const SCHEDULES_LOADING = "SCHEDULES_LOADING";
export const SCHEDULES_LOADING_FAILED = "SCHEDULES_LOADING_FAILED";
export const SHOW_ALL_SCHEDULES = "SHOW_ALL_SCHEDULES";
export const ADD_NEW_SCHEDULE = "ADD_NEW_SCHEDULE";
export const REMOVE_SCHEDULE = "REMOVE_SCHEDULE";
