export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_LOADING_FAILED = "DISHES_LOADING_FAILED";
export const SHOW_ALL_DISHES = "SHOW_ALL_DISHES";
export const ADD_NEW_DISH = "ADD_NEW_DISH";
