export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_LOADING_FAILED = "DISHES_LOADING_FAILED";
export const SHOW_ALL_DISHES = "SHOW_ALL_DISHES";
export const ADD_NEW_DISH_FAILED = "ADD_NEW_DISH_FAILED";
export const EDIT_DISH_FAILED = "EDIT_DISH_FAILED";
export const DELETE_DISH_FAILED = "DELETE_DISH_FAILED";
