export const LOCATIONS_LOADING = "LOCATIONS_LOADING";
export const LOCATIONS_LOADING_FAILED = "LOCATIONS_LOADING_FAILED";
export const SHOW_ALL_LOCATIONS = "SHOW_ALL_LOCATIONS";
export const ADD_NEW_LOCATION_FAILED = "ADD_NEW_LOCATION_FAILED";
export const EDIT_LOCATION_FAILED = "EDIT_LOCATION_FAILED";
export const DELETE_LOCATION_FAILED = "DELETE_LOCATION_FAILED";
