export const LOCATIONS_LOADING = "LOCATIONS_LOADING";
export const LOCATIONS_LOADING_FAILED = "LOCATIONS_LOADING_FAILED";
export const SHOW_ALL_LOCATIONS = "SHOW_ALL_LOCATIONS";
export const ADD_NEW_LOCATION = "ADD_NEW_LOCATION";
