POST {{ host }}/attendances
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "scheduleUuid": "aa6ff83d-b07d-4cb0-a414-7172391dd12b",
  "userUuid": "4207d44e-3d53-4b28-b43a-ae42f8204b9c",
  "isAttending": "true"
}

###

GET {{ host }}/attendances
CHEF_SESSION: {{ session }}

###
GET {{ host }}/attendances/upcoming
CHEF_SESSION: {{ session }}
###

GET {{ host }}/attendances/1dcbc463-f6d1-4164-aaa0-deb17f06cf59
CHEF_SESSION: {{ session }}
###

PUT {{ host }}/attendances/1dcbc463-f6d1-4164-aaa0-deb17f06cf59
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "isAttending": "false" }

###
