POST {{ host }}/users
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "name": "Maria do Carmo",
  "emailAddress": "maria.do.carmo@lunatech.nl",
  "locationUuid": "4f3a4488-241b-42f7-8c4e-de50fe4d1f57",
  "isVegetarian": "false",
  "hasHalalRestriction": "false",
  "hasNutsRestriction": "false",
  "hasSeafoodRestriction": "false",
  "hasPorkRestriction": "true",
  "hasBeefRestriction": "false",
  "isGlutenIntolerant": "false",
  "isLactoseIntolerant": "true",
  "otherRestrictions": "spicy food"
}

###

GET {{ host }}/users
CHEF_SESSION: {{ session }}

###

GET {{ host }}/users/token-generation
CHEF_SESSION: {{ session }}

###

GET {{ host }}/users/upcoming
Authorization: Bearer {{token}}
###

GET {{ host }}/users/f0daa634-8ec7-4fef-88c7-a92d608b6eea
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/users/3529bd57-94b7-4e82-b3d4-132c38d5b188
Content-Type: application/json
CHEF_SESSION: {{ session }}

{
  "locationUuid": "3d13f21d-a96e-4fd2-a2a9-3077f2729caf",
  "isVegetarian": "false",
  "hasHalalRestriction": "true",
  "hasNutsRestriction": "false",
  "hasSeafoodRestriction": "false",
  "hasPorkRestriction": "true",
  "hasBeefRestriction": "false",
  "isGlutenIntolerant": "false",
  "isLactoseIntolerant": "true",
  "otherRestrictions": "I like vegetarian food a lot"
}

###

DELETE {{ host }}/users/e106ce93-89e5-4164-9698-8df9dbe354bd
CHEF_SESSION: {{ session }}

###

