POST {{ host }}/dishes
Content-Type: application/json

{ "name": "Lasagna",
  "description": "Lasagna de ragu e espinafres",
  "isVegetarian": "false",
  "hasNuts": "false",
  "hasSeafood": "false",
  "hasPork": "true",
  "hasBeef": "false",
  "isGlutenFree": "false",
  "hasLactose": "false"
}

###

GET {{ host }}/dishes

###

GET {{ host }}/dishes/7399b112-59a2-44d7-bd95-c4df1dfd63e9

###

PUT {{ host }}/dishes/7399b112-59a2-44d7-bd95-c4df1dfd63e9
Content-Type: application/json

{
  "name": "Lasagna italiana",
  "description": "Lasagna de ragu e espinafres",
  "isVegetarian": "false",
  "hasSeafood": "false",
  "hasPork": "true",
  "hasBeef": "false",
  "isGlutenFree": "false",
  "hasLactose": "false"
}

###

DELETE {{ host }}/dishes/7399b112-59a2-44d7-bd95-c4df1dfd63e9

###

