POST {{ host }}/offices
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "city": "Rotterdam",
  "country": "Netherlands"
}

###

GET {{ host }}/offices
Authorization: Bearer {{ token }}

###

GET {{ host }}/offices/82ea2b48-27d8-4b52-994b-9b4fdd377195
Authorization: Bearer {{ token }}

###

PUT {{ host }}/offices/61edaf14-b018-4ffa-afba-dc5844426176
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "city": "Rotterdam",
  "country": "The Netherlands"
}

###

DELETE {{ host }}/offices/61edaf14-b018-4ffa-afba-dc5844426176
Authorization: Bearer {{ token }}

###
