POST {{ host }}/offices
Content-Type: application/json
CHEF_SESSION: {{ session }}

{
  "city": "Rotterdam",
  "country": "Netherlands"
}

###

GET {{ host }}/offices
CHEF_SESSION: {{ session }}

###

GET {{ host }}/offices/82ea2b48-27d8-4b52-994b-9b4fdd377195
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/offices/61edaf14-b018-4ffa-afba-dc5844426176
Content-Type: application/json
CHEF_SESSION: {{ session }}

{
  "city": "Rotterdam",
  "country": "The Netherlands"
}

###

DELETE {{ host }}/offices/61edaf14-b018-4ffa-afba-dc5844426176
CHEF_SESSION: {{ session }}

###
