POST {{ host }}/dishes
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "name": "Lasagna",
  "description": "Lasagna de ragu e espinafres",
  "isVegetarian": "false",
  "isHalal": "true",
  "hasNuts": "false",
  "hasSeafood": "false",
  "hasPork": "true",
  "hasBeef": "false",
  "isGlutenFree": "false",
  "hasLactose": "false"
}

###

GET {{ host }}/dishes
CHEF_SESSION: {{ session }}

###

GET {{ host }}/dishes/7399b112-59a2-44d7-bd95-c4df1dfd63e9
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/dishes/e3f4a940-8064-4d66-ba21-23b1edb04687
Content-Type: application/json
CHEF_SESSION: {{ session }}

{
  "name": "Lasagna italiana",
  "description": "Lasagna de ragu e espinafres",
  "isVegetarian": "false",
  "isHalal": "true",
  "hasNuts": "false",
  "hasSeafood": "false",
  "hasPork": "false",
  "hasBeef": "true",
  "isGlutenFree": "false",
  "hasLactose": "false"
}

###

DELETE {{ host }}/dishes/7399b112-59a2-44d7-bd95-c4df1dfd63e9
CHEF_SESSION: {{ session }}

###

