POST {{ host }}/schedules
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid": "4ebdc2ba-57eb-454d-a07a-068bd0c8873a",
  "date": "2020-04-20",
  "location": "82ea2b48-27d8-4b52-994b-9b4fdd377195"
}

###

GET {{ host }}/schedules
CHEF_SESSION: {{ session }}

###

GET {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid": "bc868425-74c4-4c74-9cb0-ec789d8d474d",
  "date": "2020-04-25",
  "location": "61edaf14-b018-4ffa-afba-dc5844426176"
}

###

DELETE {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
CHEF_SESSION: {{ session }}

###

