POST {{ host }}/schedules
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid":"3d396a7d-3628-43b6-bfbe-c5c69355d560",
  "locationUuid":"425f62da-56c7-4167-9653-cccb8b4c2f17",
  "date":"2020-06-30"
}

###

GET {{ host }}/schedules
CHEF_SESSION: {{ session }}

###

GET {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid": "bc868425-74c4-4c74-9cb0-ec789d8d474d",
  "date": "2020-04-25",
  "locationUuid": "61edaf14-b018-4ffa-afba-dc5844426176"
}

###

DELETE {{ host }}/schedules/4403ce6b-24b5-40b2-8482-211a1da7731f
CHEF_SESSION: {{ session }}

###

DELETE {{ host }}/schedules/undefined
CHEF_SESSION: {{ session }}

###

