
GET {{ host }}/schedulesWithMenusInfo
CHEF_SESSION: {{ session }}

###

GET {{ host }}/schedulesWithMenusInfo?fromdate=2021-08-01
CHEF_SESSION: {{ session }}

###

GET {{ host }}/schedulesWithMenusInfo?fromdate=2021-08-01&location=3915e475-9fb0-4d81-8664-55bcc9c8400b
CHEF_SESSION: {{ session }}

###


