POST {{ host }}/recurrentschedules
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid":"36cb6be6-6ded-447a-8273-57636b3b3675",
  "locationUuid":"8b06e81d-4065-4139-bb42-88ef31393227",
  "repetitionDays":"07",
  "nextDate":"2022-07-30"
}


###

GET {{ host }}/recurrentschedules
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/recurrentschedules/038e2c7e-bb93-4f14-a9f9-5
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "menuUuid":"36cb6be6-6ded-447a-8273-57636b3b3675",
  "locationUuid":"8b06e81d-4065-4139-bb42-88ef31393227",
  "repetitionDays":"14",
  "nextDate":"2022-07-30"
}

###

DELETE {{ host }}/recurrentschedules/038e2c7e-bb93-4f14-a9f9-d02734545805
CHEF_SESSION: {{ session }}

###

DELETE {{ host }}/recurrentschedules/undefined
CHEF_SESSION: {{ session }}

###

