POST {{ host }}/users
Content-Type: application/json
CHEF_SESSION: {{ session }}

{ "name": "Leonor",
  "emailAddress": "leonor.boga@lunatech.nl",
  "locationUuid": "5a7865b3-ed05-4569-aae5-d38d8a02c490",
  "isVegetarian": "false",
  "hasNutsRestriction": "false",
  "hasSeafoodRestriction": "false",
  "hasPorkRestriction": "true",
  "hasBeefRestriction": "false",
  "isGlutenIntolerant": "false",
  "isLactoseIntolerant": "false",
  "otherRestrictions": ""
}

###

GET {{ host }}/users
CHEF_SESSION: {{ session }}

###

GET {{ host }}/users/f0daa634-8ec7-4fef-88c7-a92d608b6eea
CHEF_SESSION: {{ session }}

###

PUT {{ host }}/users/f0daa634-8ec7-4fef-88c7-a92d608b6eea
Content-Type: application/json
CHEF_SESSION: {{ session }}

{
  "name": "Leonor",
  "emailAddress": "leonor.boga@lunatech.nl",
  "locationUuid": "61edaf14-b018-4ffa-afba-dc5844426176",
  "isInactive": "false",
  "isVegetarian": "false",
  "hasNutsRestriction": "false",
  "hasSeafoodRestriction": "false",
  "hasPorkRestriction": "true",
  "hasBeefRestriction": "false",
  "isGlutenIntolerant": "false",
  "isLactoseIntolerant": "true",
  "otherRestrictions": "I like vegetarian food a lot"
}

###

DELETE {{ host }}/users/e106ce93-89e5-4164-9698-8df9dbe354bd
CHEF_SESSION: {{ session }}

###

