export const ATTENDANCE_LOADING = "ATTENDANCE_LOADING";
export const ATTENDANCE_LOADING_FAILED = "ATTENDANCE_LOADING_FAILED";
export const SHOW_ALL_ATTENDANCE = "SHOW_ALL_ATTENDANCE";
export const SHOW_NEW_ATTENDANCE = "SHOW_NEW_ATTENDANCE";
export const EDIT_ATTENDANCE_FAILED = "EDIT_ATTENDANCE_FAILED";
