export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOADING_ERROR = "USER_PROFILE_LOADING_ERROR";
export const USER_PROFILE_SAVE_ERROR = "USER_PROFILE_SAVE_ERROR";
