export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const TOKEN_GENERATED = "TOKEN_GENERATED";
export const TOKEN_GENERATING = "TOKEN_GENERATING";

export const TOKEN_GENERATION_ERROR = "TOKEN_GENERATION_ERROR";

export const TOKEN_CLEAR = "TOKEN_CLEAR";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOADING_ERROR = "USER_PROFILE_LOADING_ERROR";
export const USER_PROFILE_SAVE_ERROR = "USER_PROFILE_SAVE_ERROR";
