export const OFFICES_LOADING = "OFFICES_LOADING";
export const OFFICES_LOADING_FAILED = "OFFICES_LOADING_FAILED";
export const SHOW_ALL_OFFICES = "SHOW_ALL_OFFICES";
export const ADD_NEW_OFFICE_FAILED = "ADD_NEW_OFFICE_FAILED";
export const EDIT_OFFICE_FAILED = "EDIT_OFFICE_FAILED";
export const DELETE_OFFICE_FAILED = "DELETE_OFFICE_FAILED";
