// locations
export const LOCATIONS_LOADING = "LOCATIONS_LOADING";
export const LOCATIONS_LOADING_FAILED = "LOCATIONS_LOADING_FAILED";
export const SHOW_ALL_LOCATIONS = "SHOW_ALL_LOCATIONS";
export const ADD_NEW_LOCATION = "ADD_NEW_LOCATION";

// dishes
export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_LOADING_FAILED = "DISHES_LOADING_FAILED";
export const SHOW_ALL_DISHES = "SHOW_ALL_DISHES";
export const ADD_NEW_DISH = "ADD_NEW_DISH";
